// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: Hello1.proto

package grpc_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Hello1Client is the client API for Hello1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Hello1Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error)
}

type hello1Client struct {
	cc grpc.ClientConnInterface
}

func NewHello1Client(cc grpc.ClientConnInterface) Hello1Client {
	return &hello1Client{cc}
}

func (c *hello1Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/com.test.Hello1/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hello1Client) Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error) {
	out := new(HelloworldResponse)
	err := c.cc.Invoke(ctx, "/com.test.Hello1/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Hello1Server is the server API for Hello1 service.
// All implementations must embed UnimplementedHello1Server
// for forward compatibility
type Hello1Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error)
	mustEmbedUnimplementedHello1Server()
}

// UnimplementedHello1Server must be embedded to have forward compatible implementations.
type UnimplementedHello1Server struct {
}

func (UnimplementedHello1Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedHello1Server) Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedHello1Server) mustEmbedUnimplementedHello1Server() {}

// UnsafeHello1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Hello1Server will
// result in compilation errors.
type UnsafeHello1Server interface {
	mustEmbedUnimplementedHello1Server()
}

func RegisterHello1Server(s grpc.ServiceRegistrar, srv Hello1Server) {
	s.RegisterService(&Hello1_ServiceDesc, srv)
}

func _Hello1_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hello1Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.test.Hello1/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hello1Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello1_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hello1Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.test.Hello1/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hello1Server).Helloworld(ctx, req.(*HelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hello1_ServiceDesc is the grpc.ServiceDesc for Hello1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.test.Hello1",
	HandlerType: (*Hello1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Hello1_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Hello1_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Hello1.proto",
}
